# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4c71e1f66a22fc2dd6f76521e7048078d9f16eea7efb5d583cfd15ac508c1423439b36992a1ea41cc7f0b51b4a08f0126c86cfb74a1f9bfea10761e382b77aa

test:
  secret_key_base: 721e5d95b526e441964c672b182491f20241eafcfd2bd2baae631b25c331a86bd7c425fca659f0d6e99901e3c6c64cde2df482dee0afbf6de91692110c529d03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
